package service

import (
	"context"
	"errors"
	"fmt"
	"math/rand"
	"net/url"

	"github.com/apnaumov/url-shortener.git/internal/logger"
	"github.com/apnaumov/url-shortener.git/internal/model"
	"github.com/apnaumov/url-shortener.git/internal/repository"
	"go.uber.org/zap"
)

type UrlShortenerService struct {
	shortenerUrls repository.UrlStorage
	urlBaseAddr   string
	logger        *zap.Logger
}

func NewUrlShortenerService(urlBaseAddr string, urlStorage repository.UrlStorage) (*UrlShortenerService, error) {
	url, err := url.Parse(urlBaseAddr)
	if err != nil {
		return nil, err
	}

	shortenerLogger, err := logger.InitializeRootLogger("shortener_service", "info")

	urlShortenerService := &UrlShortenerService{
		urlBaseAddr:   url.String(),
		shortenerUrls: urlStorage,
		logger:        shortenerLogger,
	}

	return urlShortenerService, nil
}

func (shortenerService *UrlShortenerService) GetStorage() repository.UrlStorage {
	return shortenerService.shortenerUrls
}

func (shortenerService *UrlShortenerService) OnServerShutdown() error {
	return shortenerService.shortenerUrls.OnServerShutdown()
}

func (shortenerService *UrlShortenerService) GetFullURL(ctx context.Context, shortURL string) (model.RequestURLData, error) {
	v, err := shortenerService.shortenerUrls.GetFullUrl(ctx, shortURL)
	if err != nil {
		if errors.Is(err, repository.NotFoundError) {
			return model.RequestURLData{}, fmt.Errorf("can't find URL by the key %q. Error: %w", shortURL, err)
		}
		return model.RequestURLData{}, err
	}
	return v, nil
}

func (shortenerService *UrlShortenerService) SetFullURL(ctx context.Context, urlData model.RequestURLData) (model.ResponceURLData, error) {
	const maxAttemptsToGenerateKey = 10
	var shortURL string

	for range maxAttemptsToGenerateKey {
		shortURL = generateShortKey()

		urlRecord := model.URLRecord{ShortURL: shortURL, UrlData: urlData}

		err := shortenerService.shortenerUrls.SetUrl(ctx, urlRecord)
		if err != nil {
			if errors.Is(err, repository.ShortUrlCollisionError) {
				shortenerService.logger.Debug("Can't generate short key because of collision.", zap.String("short key", shortURL))
				continue
			} else {
				return model.ResponceURLData{}, err
			}
		} else {
			break
		}
	}

	resShortUrl, err := url.JoinPath(shortenerService.urlBaseAddr, shortURL)
	if err != nil {
		return model.ResponceURLData{}, err
	}

	return model.ResponceURLData{ShortUrl: resShortUrl, CorrelationId: urlData.CorrelationId}, nil
}

// Generate a random short key (generated by AI)
func generateShortKey() string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	const keyLength = 6

	b := make([]byte, keyLength)
	for i := range b {
		b[i] = charset[rand.Intn(len(charset))]
	}
	return string(b)
}
