package service

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/rand"
	"net/url"
	"os"

	"github.com/apnaumov/url-shortener.git/internal/logger"
	"github.com/apnaumov/url-shortener.git/internal/model"
	"github.com/apnaumov/url-shortener.git/internal/repository"
	"go.uber.org/zap"
)

type UrlShortenerService struct {
	shortenerUrls   *repository.Storage[string]
	urlBaseAddr     string
	fileStoragePath string
	logger          *zap.Logger
}

func NewUrlShortenerService(urlBaseAddr string, fileStoragePath string) (*UrlShortenerService, error) {
	url, err := url.Parse(urlBaseAddr)
	if err != nil {
		return nil, err
	}

	shortenerLogger, err := logger.InitializeRootLogger("shortener_service", "info")

	urlShortenerService := &UrlShortenerService{
		urlBaseAddr:     url.String(),
		fileStoragePath: fileStoragePath,
		shortenerUrls:   repository.NewStorage[string](),
		logger:          shortenerLogger,
	}

	if err := urlShortenerService.loadFromFile(); err != nil {
		urlShortenerService.logger.Warn("Error while load configuration from file", zap.String("error", err.Error()))
	}

	return urlShortenerService, nil
}

func (shortenerService *UrlShortenerService) GetFullURL(shortURL string) (string, error) {
	v, err := shortenerService.shortenerUrls.Get(shortURL)
	if err != nil {
		return "", fmt.Errorf("can't find URL by the key %q. Error: %w", shortURL, err)
	}
	return v, nil
}

func (shortenerService *UrlShortenerService) SetFullURL(fullURL string) (string, error) {
	const maxAttemptsToGenerateKey = 10
	var shortURL string

	for range maxAttemptsToGenerateKey {
		shortURL = generateShortKey()

		err := shortenerService.shortenerUrls.Set(shortURL, fullURL)
		if err != nil {
			if errors.Is(err, repository.CollisionError) {
				shortenerService.logger.Debug("Can't generate short key because of collision.", zap.String("short key", shortURL))
				continue
			} else {
				return "", err
			}
		} else {
			break
		}
	}

	return url.JoinPath(shortenerService.urlBaseAddr, shortURL)
}

func (shortenerService *UrlShortenerService) loadFromFile() error {
	file, err := os.OpenFile(shortenerService.fileStoragePath, os.O_RDONLY, 0666)
	if err != nil {
		return err
	}
	defer file.Close()

	jsonDecoder := json.NewDecoder(file)

	for {
		record := model.URLFileRecord{}
		err := jsonDecoder.Decode(&record)
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}

		if err := shortenerService.shortenerUrls.Set(record.ShortURL, record.OriginalURL); err != nil {
			return err
		}
	}

	return nil
}

func (shortenerService *UrlShortenerService) SaveToFile() error {
	file, err := os.OpenFile(shortenerService.fileStoragePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0666)
	if err != nil {
		return err
	}

	storageContainer := shortenerService.shortenerUrls.GetAll()

	jsonEncoder := json.NewEncoder(file)

	for k, v := range storageContainer {
		if err := jsonEncoder.Encode(model.URLFileRecord{ShortURL: k, OriginalURL: v}); err != nil {
			return err
		}
	}

	return nil
}

// Generate a random short key (generated by AI)
func generateShortKey() string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	const keyLength = 6

	b := make([]byte, keyLength)
	for i := range b {
		b[i] = charset[rand.Intn(len(charset))]
	}
	return string(b)
}
