package service

import (
	"fmt"
	"math/rand"
	"net/url"
	"sync"
	"time"
)

type UrlShortenerService struct {
	mu            sync.RWMutex
	urlBaseAddr   string
	shortenerUrls map[string]string
}

func NewUrlShortenerService(urlBaseAddr string) (*UrlShortenerService, error) {
	url, err := url.Parse(urlBaseAddr)
	if err != nil {
		return nil, err
	}
	if url.Path == "" {
		url.Path = "/"
	}

	return &UrlShortenerService{
		urlBaseAddr:   url.String(),
		shortenerUrls: make(map[string]string),
	}, nil
}

func (shortenerService *UrlShortenerService) GetFullURL(shortURL string) (string, error) {
	shortenerService.mu.RLock()
	defer shortenerService.mu.RUnlock()
	v, ok := shortenerService.shortenerUrls[shortURL]
	if !ok {
		return "", fmt.Errorf("Can't find URL")
	}
	return v, nil
}

func (shortenerService *UrlShortenerService) SetFullURL(fullURL string) string {
	shortURL := generateShortKey()

	shortenerService.mu.Lock()
	defer shortenerService.mu.Unlock()
	shortenerService.shortenerUrls[shortURL] = fullURL

	return shortenerService.urlBaseAddr + shortURL
}

// Generate a random short key (generated by AI)
func generateShortKey() string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	const keyLength = 6

	rand.Seed(time.Now().UnixNano())
	b := make([]byte, keyLength)
	for i := range b {
		b[i] = charset[rand.Intn(len(charset))]
	}
	return string(b)
}
